---
- hosts: endor
  remote_user: root

  tasks:
    # Configure Nginx
    - name: ensure the nginx ssl directory exists
      command: mkdir /etc/nginx/ssl creates=/etc/nginx/ssl

    - name: copy the nginx config
      copy: src=./files/nginx.conf dest=/etc/nginx/nginx.conf
      notify:
      - restart nginx

    - name: remove default nginx site
      command: rm -rf /etc/nginx/sites-enabled/default removes=/etc/nginx/sites-enabled/default
      notify:
      - restart nginx

    - name: copy docker-gen nginx template
      copy: src=./files/docker_nginx.tmpl dest=/etc/nginx/docker_nginx.tmpl
      notify:
      - restart dockergen

    - name: copy ssl certificates (1/2)
      copy: src=./files/server.crt dest=/etc/nginx/ssl/server.crt mode=600 force=no

    - name: copy ssl certificates (2/2)
      copy: src=./files/server.key dest=/etc/nginx/ssl/server.key mode=600 force=no

    # Setup SSH
    - name: ensure the ssh directory exists
      command: mkdir ~/.ssh creates=~/.ssh

    - name: copy the ssh keys (1/2)
      copy: src=./files/id_rsa dest=~/.ssh/id_rsa mode=600 force=no

    - name: copy the ssh keys (2/2)
      copy: src=./files/id_rsa.pub dest=~/.ssh/id_rsa.pub mode=644 force=no

  handlers:
    - include: ../../shared/ansible/handlers/restart_nginx.yml
    - include: ../../shared/ansible/handlers/restart_dockergen.yml
