---
- hosts: endor
  remote_user: root

  vars_files:
    - ./variables.yml

  tasks:
    - name: ensure nginx is running
      service: name=nginx state=started

    - include: ./tasks/clone.yml

    - name: remove old container
      docker: image=blog name=blog_consumer_1 state=absent

    - name: remove old docker image
      docker_image: path=/root/blog name="blog" state=absent

    - name: build new docker image
      docker_image: path=/root/blog name="blog" state=present

    - name: start new container
      docker: "image=blog name=blog_consumer_1 state=running ports=3100:3000 env=VIRTUAL_HOST=new.stevenschobert.com,NODE_ENV=production,GAUGES_KEY={{ gauges_key }},COUCH_URL={{ couch_url }},COUCH_PORT={{ couch_port }},COUCH_DB={{ couch_db }},COUCH_USER={{ couch_user }},COUCH_PASS={{ couch_password }}"
      notify:
      - restart dockergen

  handlers:
    - name: restart dockergen
      service: name=dockergen state=restarted
